const SCALE_FRACTION = 5 / 16;
const LINE_SIZE_FRACTION = 1 / 200;
const TEXT_SIZE_FRACTION = 2 / 48;
const TEXT_MAX_WIDTH_FRACTION = 1 / 6;
const TEXT_POSITION_FRACTION = 5 / 12;
const SCOREPOINT_SIZE_FRACTION = 1 / 140;

export {
  SCALE_FRACTION,
  LINE_SIZE_FRACTION,
  TEXT_SIZE_FRACTION,
  TEXT_MAX_WIDTH_FRACTION,
  TEXT_POSITION_FRACTION,
  SCOREPOINT_SIZE_FRACTION,
};
