const SCALE_FRACTION = 5 / 16;
const TEXT_SIZE_FRACTION = 2 / 48;
const TEXT_MAX_WIDTH_FRACTION = 1 / 6;
const TEXT_POSITION_FRACTION = 5 / 12;

export {
  SCALE_FRACTION,
  TEXT_SIZE_FRACTION,
  TEXT_MAX_WIDTH_FRACTION,
  TEXT_POSITION_FRACTION,
};
