name: Android build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Setup Java v1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Add SDK path to settings
        run: 'echo "sdk.dir = $HOME/.android/sdk" > ./local.properties'
      - name: Build
        run: cd ./android && ./gradlew clean build --no-daemon --no-build-cache
