name: Android build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Setup Java v1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Add SDK path to settings
        run: 'echo "sdk.dir = /usr/local/lib/android/sdk" > ./local.properties'
      - name: Build
        run: cd ./android && ./gradlew build
      - name: Notify success in Slack channel
        if: ${{ success() }}
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          token: ${{ secrets.SLACK_APP_TOKEN }}
          path: ./android/build/outputs/apk/release/apk-release.apk
          channel: growup_mobile_build_notifications
          initial_comment: "GrowUp Mobile build success!\nHere is the file:"
      - name: Notify failure in Slack channel
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v2.3.2
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_APP_TOKEN }}
          slack-channel: growup_mobile_build_notifications
          slack-text: "GrowUp Mobile build failed :("
          slack-optional-icon_emoji: ":calling:"
          slack-optional-as_user: false
