name: Android build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Setup Java v1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Add SDK path to settings
        run: 'echo "sdk.dir = /usr/local/lib/android/sdk" > ./android/local.properties'
      - name: Add .env file
        env:
          DOTENV_FILE: ${{ secrets.DOTENV_FILE }}
        run: 'echo $DOTENV_FILE > ./.env'
      - name: Add Android google-services.json file
        env:
          ANDROID_GOOGLE_SERVICES_FILE: ${{ secrets.ANDROID_GOOGLE_SERVICES_FILE }}
        run: 'echo $ANDROID_GOOGLE_SERVICES_FILE > ./android/app/google-services.json'
      - name: Add IOS GoogleService-Info.plist file
        env:
          IOS_GOOGLE_SERVICES_FILE: ${{ secrets.IOS_GOOGLE_SERVICES_FILE }}
        run: 'echo $IOS_GOOGLE_SERVICES_FILE > ./ios/growupmobile/GoogleService-Info.plist'
      - name: Build
        run: cd ./android && ./gradlew clean assembleRelease
      - name: Notify failure in Slack channel (if failed)
        if: ${{ failure() }}
        uses: joshmgross/send-slack-message@v1.0.1
        with:
          slack-token: ${{ secrets.SLACK_APP_TOKEN }}
          channel: C032QNEGYHF
          message: "GrowUp Mobile build failed in branch ${{ github.ref }} :("
      - name: Notify success in Slack channel
        if: ${{ success() }}
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          token: ${{ secrets.SLACK_APP_TOKEN }}
          path: ./android/app/build/outputs/apk/release/app-release.apk
          channel: growup_mobile_build_notifications
          initial_comment: "GrowUp Mobile build success in branch ${{ github.ref }}!\nHere is the file:"
